[package]
name = "water-reminder"
version = "0.1.0"
authors = ["nakkapeddi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
notify-rust = "^3"